[2023-08-28T23:09:30.360-0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Investimento_api.Insert_Postgres manual__2023-08-29T02:08:54.698762+00:00 [queued]>
[2023-08-28T23:09:30.365-0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Investimento_api.Insert_Postgres manual__2023-08-29T02:08:54.698762+00:00 [queued]>
[2023-08-28T23:09:30.365-0300] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-28T23:09:30.384-0300] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): Insert_Postgres> on 2023-08-29 02:08:54.698762+00:00
[2023-08-28T23:09:30.387-0300] {standard_task_runner.py:57} INFO - Started process 30179 to run task
[2023-08-28T23:09:30.391-0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Investimento_api', 'Insert_Postgres', 'manual__2023-08-29T02:08:54.698762+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmphsgs_ng6']
[2023-08-28T23:09:30.392-0300] {standard_task_runner.py:85} INFO - Job 40: Subtask Insert_Postgres
[2023-08-28T23:09:30.429-0300] {task_command.py:410} INFO - Running <TaskInstance: Investimento_api.Insert_Postgres manual__2023-08-29T02:08:54.698762+00:00 [running]> on host VMEnricolm.myguest.virtualbox.org
[2023-08-28T23:09:30.507-0300] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Investimento_api' AIRFLOW_CTX_TASK_ID='Insert_Postgres' AIRFLOW_CTX_EXECUTION_DATE='2023-08-29T02:08:54.698762+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-29T02:08:54.698762+00:00'
[2023-08-28T23:09:30.508-0300] {sql.py:265} INFO - Executing: COPY Apple_table FROM '/home/enricolm/Documents/Sprinklr_Airflow/dadosvm/Airflow_Investimento/datalake/Raw/Data=2023-08-27' CSV HEADER;
[2023-08-28T23:09:30.514-0300] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/enricolm/Documents/Sprinklr_Airflow/dadosvm/Airflow_Investimento/venv/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 266, in execute
    hook = self.get_db_hook()
  File "/home/enricolm/Documents/Sprinklr_Airflow/dadosvm/Airflow_Investimento/venv/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 181, in get_db_hook
    return self._hook
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/enricolm/Documents/Sprinklr_Airflow/dadosvm/Airflow_Investimento/venv/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 143, in _hook
    conn = BaseHook.get_connection(self.conn_id)
  File "/home/enricolm/Documents/Sprinklr_Airflow/dadosvm/Airflow_Investimento/venv/lib/python3.10/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/enricolm/Documents/Sprinklr_Airflow/dadosvm/Airflow_Investimento/venv/lib/python3.10/site-packages/airflow/models/connection.py", line 463, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `` isn't defined
[2023-08-28T23:09:30.516-0300] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=Investimento_api, task_id=Insert_Postgres, execution_date=20230829T020854, start_date=20230829T020930, end_date=20230829T020930
[2023-08-28T23:09:30.620-0300] {standard_task_runner.py:104} ERROR - Failed to execute job 40 for task Insert_Postgres (The conn_id `` isn't defined; 30179)
[2023-08-28T23:09:30.664-0300] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-28T23:09:30.674-0300] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
