[2023-08-28T23:05:01.822-0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Investimento_api.Insert_Postgres manual__2023-08-29T02:04:19.335344+00:00 [queued]>
[2023-08-28T23:05:01.831-0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Investimento_api.Insert_Postgres manual__2023-08-29T02:04:19.335344+00:00 [queued]>
[2023-08-28T23:05:01.836-0300] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-28T23:05:02.126-0300] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): Insert_Postgres> on 2023-08-29 02:04:19.335344+00:00
[2023-08-28T23:05:02.139-0300] {standard_task_runner.py:57} INFO - Started process 29636 to run task
[2023-08-28T23:05:02.144-0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Investimento_api', 'Insert_Postgres', 'manual__2023-08-29T02:04:19.335344+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpg1_pl1iw']
[2023-08-28T23:05:02.147-0300] {standard_task_runner.py:85} INFO - Job 36: Subtask Insert_Postgres
[2023-08-28T23:05:02.286-0300] {task_command.py:410} INFO - Running <TaskInstance: Investimento_api.Insert_Postgres manual__2023-08-29T02:04:19.335344+00:00 [running]> on host VMEnricolm.myguest.virtualbox.org
[2023-08-28T23:05:02.865-0300] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Investimento_api' AIRFLOW_CTX_TASK_ID='Insert_Postgres' AIRFLOW_CTX_EXECUTION_DATE='2023-08-29T02:04:19.335344+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-29T02:04:19.335344+00:00'
[2023-08-28T23:05:02.868-0300] {sql.py:265} INFO - Executing: COPY Apple_table FROM '/home/enricolm/Documents/Sprinklr_Airflow/dadosvm/Airflow_Investimento/datalake/Raw/Data=2023-08-27' CSV HEADER;
[2023-08-28T23:05:02.876-0300] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/enricolm/Documents/Sprinklr_Airflow/dadosvm/Airflow_Investimento/venv/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 266, in execute
    hook = self.get_db_hook()
  File "/home/enricolm/Documents/Sprinklr_Airflow/dadosvm/Airflow_Investimento/venv/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 181, in get_db_hook
    return self._hook
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/enricolm/Documents/Sprinklr_Airflow/dadosvm/Airflow_Investimento/venv/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 143, in _hook
    conn = BaseHook.get_connection(self.conn_id)
  File "/home/enricolm/Documents/Sprinklr_Airflow/dadosvm/Airflow_Investimento/venv/lib/python3.10/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/enricolm/Documents/Sprinklr_Airflow/dadosvm/Airflow_Investimento/venv/lib/python3.10/site-packages/airflow/models/connection.py", line 463, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `` isn't defined
[2023-08-28T23:05:02.972-0300] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=Investimento_api, task_id=Insert_Postgres, execution_date=20230829T020419, start_date=20230829T020501, end_date=20230829T020502
[2023-08-28T23:05:03.103-0300] {standard_task_runner.py:104} ERROR - Failed to execute job 36 for task Insert_Postgres (The conn_id `` isn't defined; 29636)
[2023-08-28T23:05:03.127-0300] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-28T23:05:03.156-0300] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
